const mongoose = require('mongoose');
const jwt = require('jsonwebtoken');
const User = require('../models/User');
const OtpSession = require('../models/OtpSession');
const referralService = require('../services/referralService');
const adminLogService = require('../services/adminLogService');
const emailService = require('../services/emailService');

const JWT_SECRET = process.env.JWT_SECRET || 'super_secret_esports_key';

// Keep reference to dynamic firebase-admin if initialized
let firebaseAdmin = null;
try {
  firebaseAdmin = require('firebase-admin');
} catch (e) {
  console.warn('[Auth Controller] firebase-admin package is not accessible.');
}

/**
 * Generate standard JWT for our local private session context
 */
const generateUserToken = (user) => {
  return jwt.sign(
    {
      id: user._id,
      role: user.role || 'user',
      is2faVerified: false
    },
    JWT_SECRET,
    { expiresIn: '30d' }
  );
};

/**
 * @desc    Verify Firebase ID Token (generated by mobile OTP login) and login or register user
 * @route   POST /api/auth/firebase-login
 * @access  Public
 */
exports.firebaseLogin = async (req, res) => {
  try {
    const { idToken, inGameName, freeFireUid, email, referralCode } = req.body;

    if (!idToken) {
      return res.status(400).json({
        success: false,
        message: 'Firebase authenticating ID token is required.'
      });
    }

    // 1. Confirm Firebase App is initialised on the backend
    if (!firebaseAdmin || firebaseAdmin.apps.length === 0) {
      return res.status(503).json({
        success: false,
        message: 'Firebase Admin SDK is not completely configured in this server environment. Please utilize the Sandbox OTP endpoints for testing.',
        sandboxFallbackAvailable: true
      });
    }

    // 2. Validate token using Firebase Admin SDK
    let decodedToken;
    try {
      decodedToken = await firebaseAdmin.auth().verifyIdToken(idToken);
    } catch (verifyError) {
      return res.status(401).json({
        success: false,
        message: 'Firebase verification failed. Access token is expired or altered.',
        error: verifyError.message
      });
    }

    // Extract validated variables from verified credentials
    const { phone_number, uid } = decodedToken;

    if (!phone_number) {
      return res.status(400).json({
        success: false,
        message: 'Valid phone verification identifier was not found in the provided ID Token.'
      });
    }

    // 3. Document or find match in database
    let user = await User.findOne({ phoneNumber: phone_number });
    let isNew = false;

    if (!user) {
      isNew = true;
      
      // Clean components to satisfy strict DB schema validation constraints
      const resolvedEmail = email && email.trim() !== '' 
        ? email.toLowerCase().trim() 
        : `${phone_number.replace('+', '')}@battlezone.com`;

      // Check if email already registered (if so, append random suffix to avoid unique constraint)
      const emailExists = await User.findOne({ email: resolvedEmail });
      const finalEmail = emailExists 
        ? `${phone_number.replace('+', '')}-${Math.floor(1000 + Math.random() * 9000)}@battlezone.com`
        : resolvedEmail;

      const defaultInGameName = inGameName && inGameName.trim() !== ''
        ? inGameName.trim()
        : `Gamer_${phone_number.slice(-4)}`;

      const defaultFreeFireUid = freeFireUid && freeFireUid.trim() !== ''
        ? freeFireUid.trim()
        : `FF_${phone_number.slice(-4)}`;

      // Generate customized referral hash
      const userReferralCode = await referralService.generateUniqueReferralCode(defaultInGameName);

      // Start database atomic transaction to sign up & award loyalty refer parameters
      const session = await mongoose.startSession();
      session.startTransaction();

      try {
        user = new User({
          phoneNumber: phone_number,
          email: finalEmail,
          inGameName: defaultInGameName,
          freeFireUid: defaultFreeFireUid,
          referralCode: userReferralCode,
          role: 'user'
        });

        await user.save({ session });

        // Apply reward if referral code exists
        if (referralCode && referralCode.trim() !== '') {
          try {
            await referralService.applyReferralCode(user._id, referralCode.trim(), session);
          } catch (refError) {
            console.warn(`[Authentication Register] Referral code apply skipped: ${refError.message}`);
          }
        }

        await session.commitTransaction();
      } catch (err) {
        await session.abortTransaction();
        throw err;
      } finally {
        session.endSession();
      }

      // Log successful registration events
      await adminLogService.logAction({
        adminId: new mongoose.Types.ObjectId(), // System Registration Routine ID
        action: 'USER_WALLET_ADJUSTMENT',
        targetType: 'User',
        targetId: user._id,
        details: `Automated sign-up completed for user with Phone number: ${phone_number}`
      });
    }

    // 4. Issue Local JWT
    const localToken = generateUserToken(user);

    return res.status(200).json({
      success: true,
      message: isNew ? 'Registration completed successfully.' : 'Sign in completed successfully.',
      isNew,
      token: localToken,
      user: {
        id: user._id,
        phoneNumber: user.phoneNumber,
        email: user.email,
        inGameName: user.inGameName,
        freeFireUid: user.freeFireUid,
        referralCode: user.referralCode,
        depositBalance: user.depositBalance,
        winningBalance: user.winningBalance,
        bonusBalance: user.bonusBalance,
        role: user.role
      }
    });

  } catch (error) {
    return res.status(500).json({
      success: false,
      message: 'Failed to process Firebase transaction.',
      error: error.message
    });
  }
};

/**
 * @desc    Simulate Sending OTP (Sandbox utility)
 * @route   POST /api/auth/sandbox/send-otp
 * @access  Public
 */
exports.sandboxSendOtp = async (req, res) => {
  try {
    const { phoneNumber } = req.body;

    if (!phoneNumber || !phoneNumber.trim()) {
      return res.status(400).json({
        success: false,
        message: 'Phone number with country prefix (e.g., +919999999999) is required.'
      });
    }

    const trimmedPhone = phoneNumber.trim();

    // Generate a secure, simulated 6-digit verification code
    // Standard test phones can have a predictable OTP
    let otpCode = '123456';
    if (trimmedPhone !== '+919999999999') {
      otpCode = Math.floor(100000 + Math.random() * 900000).toString();
    }

    // Save/Overwrite OTP target session with 5 minutes lifespan
    const expiresAt = new Date(Date.now() + 5 * 60 * 1000);

    await OtpSession.findOneAndUpdate(
      { phoneNumber: trimmedPhone },
      { otpCode, expiresAt, isVerified: false },
      { upsert: true, new: true }
    );

    console.log(`\n======================================================`);
    console.log(`[SANDBOX OTP SIMULATOR]`);
    console.log(`SMS Sent To: ${trimmedPhone}`);
    console.log(`Verification Code: ${otpCode}`);
    console.log(`======================================================\n`);

    return res.status(200).json({
      success: true,
      message: `[Sandbox] OTP sent via simulated gateway service to ${trimmedPhone}.`,
      verificationCode: otpCode, // Included for seamless end-to-end sandbox frontend UI wiring
      expirationInSeconds: 300
    });

  } catch (error) {
    return res.status(500).json({
      success: false,
      message: 'Failed to trigger simulated OTP gateway transaction.',
      error: error.message
    });
  }
};

/**
 * @desc    Verify Simulated OTP and login / create User (Sandbox utility)
 * @route   POST /api/auth/sandbox/verify-otp
 * @access  Public
 */
exports.sandboxVerifyOtp = async (req, res) => {
  try {
    const { phoneNumber, otpCode, inGameName, freeFireUid, email, referralCode } = req.body;

    if (!phoneNumber || !otpCode) {
      return res.status(400).json({
        success: false,
        message: 'Both phoneNumber and verifying otpCode parameters are required.'
      });
    }

    const trimmedPhone = phoneNumber.trim();

    // 1. Locate and check OTP Sessions validity
    const otpSession = await OtpSession.findOne({ phoneNumber: trimmedPhone });
    if (!otpSession) {
      return res.status(400).json({
        success: false,
        message: 'No active OTP verification request found for this phone number.'
      });
    }

    if (otpSession.expiresAt < new Date()) {
      return res.status(400).json({
        success: false,
        message: 'Simulated OTP transaction has expired. Please request a new code.'
      });
    }

    if (otpSession.otpCode !== otpCode.trim()) {
      return res.status(400).json({
        success: false,
        message: 'The verification code entered is incorrect.'
      });
    }

    // 2. Consume the OTP session
    await OtpSession.deleteOne({ _id: otpSession._id });

    // 3. Document or locate match in database
    let user = await User.findOne({ phoneNumber: trimmedPhone });
    let isNew = false;

    if (!user) {
      isNew = true;

      const resolvedEmail = email && email.trim() !== '' 
        ? email.toLowerCase().trim() 
        : `${trimmedPhone.replace('+', '')}@battlezone.com`;

      const emailExists = await User.findOne({ email: resolvedEmail });
      const finalEmail = emailExists 
        ? `${trimmedPhone.replace('+', '')}-${Math.floor(1000 + Math.random() * 9000)}@battlezone.com`
        : resolvedEmail;

      const defaultInGameName = inGameName && inGameName.trim() !== ''
        ? inGameName.trim()
        : `Gamer_${trimmedPhone.slice(-4)}`;

      const defaultFreeFireUid = freeFireUid && freeFireUid.trim() !== ''
        ? freeFireUid.trim()
        : `FF_${trimmedPhone.slice(-4)}`;

      const userReferralCode = await referralService.generateUniqueReferralCode(defaultInGameName);

      const session = await mongoose.startSession();
      session.startTransaction();

      try {
        user = new User({
          phoneNumber: trimmedPhone,
          email: finalEmail,
          inGameName: defaultInGameName,
          freeFireUid: defaultFreeFireUid,
          referralCode: userReferralCode,
          role: 'user'
        });

        await user.save({ session });

        if (referralCode && referralCode.trim() !== '') {
          try {
            await referralService.applyReferralCode(user._id, referralCode.trim(), session);
          } catch (refError) {
            console.warn(`[Sandbox OTP Register] Referral code apply skipped: ${refError.message}`);
          }
        }

        await session.commitTransaction();
      } catch (err) {
        await session.abortTransaction();
        throw err;
      } finally {
        session.endSession();
      }

      await adminLogService.logAction({
        adminId: new mongoose.Types.ObjectId(), // System Sandbox Registration ID
        action: 'USER_WALLET_ADJUSTMENT',
        targetType: 'User',
        targetId: user._id,
        details: `Simulated sandbox registration successfully processed for phone: ${trimmedPhone}`
      });
    }

    // 4. Generate local authentication signature
    const localToken = generateUserToken(user);

    return res.status(200).json({
      success: true,
      message: isNew ? 'Sandbox simulated signup completed.' : 'Sandbox simulated login completed.',
      isNew,
      token: localToken,
      user: {
        id: user._id,
        phoneNumber: user.phoneNumber,
        email: user.email,
        inGameName: user.inGameName,
        freeFireUid: user.freeFireUid,
        referralCode: user.referralCode,
        depositBalance: user.depositBalance,
        winningBalance: user.winningBalance,
        bonusBalance: user.bonusBalance,
        role: user.role
      }
    });

  } catch (error) {
    return res.status(500).json({
      success: false,
      message: 'Failed to fulfill sandbox validation criteria.',
      error: error.message
    });
  }
};

/**
 * @desc    Generate and Send Live Gmail SMTP OTP Code (completely secure and free)
 * @route   POST /api/auth/gmail/send-otp
 * @access  Public
 */
exports.sendLiveGmailOtp = async (req, res) => {
  try {
    const { email, purpose, gmailUser, gmailAppPassword } = req.body;

    if (!email || !email.trim() || !email.includes('@')) {
      return res.status(400).json({
        success: false,
        message: 'A valid email address is required to dispatch the verification code key.'
      });
    }

    const cleanEmail = email.trim().toLowerCase();
    
    // Support an optional client-supplied OTP code or generate a secure, high-entropy 6-digit verification code
    const otpCode = req.body.otpCode ? req.body.otpCode.toString().trim() : Math.floor(100000 + Math.random() * 900000).toString();

    // Lifespan of 10 minutes
    const expiresAt = new Date(Date.now() + 10 * 60 * 1000);

    // Store securely in database. We use the same OtpSession schema by using a virtual format for phoneNumber field or storing email values
    await OtpSession.findOneAndUpdate(
      { phoneNumber: `email:${cleanEmail}` },
      { otpCode, expiresAt, isVerified: false },
      { upsert: true, new: true }
    );

    // Call the Nodemailer free SMTP service to deliver
    await emailService.sendOtpEmail(cleanEmail, otpCode, purpose || 'Login Account Verification', gmailUser, gmailAppPassword);

    return res.status(200).json({
      success: true,
      message: `Verification code successfully generated and dispatched to ${cleanEmail} via Gmail SMTP.`
    });

  } catch (error) {
    console.error('[Gmail OTP Send Router Encounter]:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to dispatch Gmail verification code. Check your SMTP App details.',
      error: error.message
    });
  }
};

/**
 * @desc    Verify Gmail SMTP OTP and Login or Register user (completely secure and free)
 * @route   POST /api/auth/gmail/verify-otp
 * @access  Public
 */
exports.verifyLiveGmailOtp = async (req, res) => {
  try {
    const { email, otpCode, inGameName, freeFireUid, referralCode } = req.body;

    if (!email || !otpCode) {
      return res.status(400).json({
        success: false,
        message: 'Both email address and 6-digit verification code are required.'
      });
    }

    const cleanEmail = email.trim().toLowerCase();

    // 1. Locate session
    const otpSession = await OtpSession.findOne({ phoneNumber: `email:${cleanEmail}` });
    if (!otpSession) {
      return res.status(400).json({
        success: false,
        message: 'No active verification session found. Please request a new code.'
      });
    }

    if (otpSession.expiresAt < new Date()) {
      return res.status(400).json({
        success: false,
        message: 'The verification code has expired. Please request a new one.'
      });
    }

    if (otpSession.otpCode !== otpCode.trim()) {
      return res.status(400).json({
        success: false,
        message: 'The verification code entered is incorrect.'
      });
    }

    // 2. Clear verified OTP session
    await OtpSession.deleteOne({ _id: otpSession._id });

    // 3. Document or locate match in database
    let user = await User.findOne({ email: cleanEmail });
    let isNew = false;

    if (!user) {
      isNew = true;

      // Clean default names
      const defaultInGameName = inGameName && inGameName.trim() !== ''
        ? inGameName.trim()
        : `Gamer_${cleanEmail.substringBefore ? cleanEmail.substringBefore('@') : cleanEmail.split('@')[0]}`;

      const defaultFreeFireUid = freeFireUid && freeFireUid.trim() !== ''
        ? freeFireUid.trim()
        : `FF_${Math.floor(1000 + Math.random() * 9000)}`;

      // Generate customized referral hash
      const userReferralCode = await referralService.generateUniqueReferralCode(defaultInGameName);

      const session = await mongoose.startSession();
      session.startTransaction();

      try {
        user = new User({
          phoneNumber: `email:${cleanEmail}`, // Virtual phone fallback identifier to maintain schema integrity
          email: cleanEmail,
          inGameName: defaultInGameName,
          freeFireUid: defaultFreeFireUid,
          referralCode: userReferralCode,
          role: cleanEmail === 'battlezone.support@gmail.com' ? 'admin' : 'user' // Automated role allocation
        });

        await user.save({ session });

        // Apply reward if referral code exists
        if (referralCode && referralCode.trim() !== '') {
          try {
            await referralService.applyReferralCode(user._id, referralCode.trim(), session);
          } catch (refError) {
            console.warn(`[Gmail Verification Register] Referral code skipped: ${refError.message}`);
          }
        }

        await session.commitTransaction();
      } catch (err) {
        await session.abortTransaction();
        throw err;
      } finally {
        session.endSession();
      }

      await adminLogService.logAction({
        adminId: new mongoose.Types.ObjectId(),
        action: 'USER_WALLET_ADJUSTMENT',
        targetType: 'User',
        targetId: user._id,
        details: `Gmail verified sign-up completed for user email: ${cleanEmail}`
      });
    }

    // 4. Issue token
    const localToken = generateUserToken(user);

    return res.status(200).json({
      success: true,
      message: isNew ? 'Registration completed successfully.' : 'Sign in completed successfully.',
      isNew,
      token: localToken,
      user: {
        id: user._id,
        phoneNumber: user.phoneNumber,
        email: user.email,
        inGameName: user.inGameName,
        freeFireUid: user.freeFireUid,
        referralCode: user.referralCode,
        depositBalance: user.depositBalance,
        winningBalance: user.winningBalance,
        bonusBalance: user.bonusBalance,
        role: user.role
      }
    });

  } catch (error) {
    console.error('[Gmail OTP Verify Router Encounter]:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to process Gmail verification transaction.',
      error: error.message
    });
  }
};
